[package]
name = "ClipCursor"
version = "0.1.0"
authors = ["xleine"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-graphics = "0.22.2"
device_query = "0.2.8"
